version: '3'
services: 
    api:
        build: .
        network_mode: bridge
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0  --port 8000
        container_name: duka-inventory-service
        restart: always
        ports: 
            - 8000:8000