version: '3'
services: 
    api:
        build: .
        network_mode: host
        command: uvicorn main:app --reload --workers 1 --host 127.0.0.1  --port 8000
        container_name: duka-inventory-service
        restart: always
        