version: '3'
services: 
    api:
        build: .
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0  --port 8001
        container_name: duka-inventory-service
        restart: always
        ports: 
            - 8001:80
        