name: deploy-sportsgeek-api
# controls when the action will run. Triger the workflow on push
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    pull_request:
      - main
  

#  workflow is made up of one or more jobs that can run
#  sequentially or in parallel
jobs:

  # test:
  #   runs-on: ubuntu-18.04
  #   strategy:
  #     matrix:
  #       python-version: [3.5, 3.6, 3.7, 3.8]

  #   steps:
  #     - uses: actions/checkout/@v2
  #     - name: set up python
  #       uses: actions/setup-python@v2
  #     - name: install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Run tests
  #       run: |
  #         python -m unittest tests/test_basic.py

  deploy:
    # needs: [test]
    # the type of runner that the job will run on
    runs-on: ubuntu-18.04

    # represent a sequence of tasks that will be executed as part of the
    # job
    steps: 
      - name: Setup DigitalOcean SSH 
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd data
            cd duka-inventory-fastapi-service
            git pull origin main
            docker-compose -f ~/data/duka-inventory-fastapi-service/docker-compose.yml up --build -d          
          